/**
 * geo-types.ts
 * ---------------------------------------------------------------------------
 * Typed shapes for the two static GIS datasets that power the manatee
 * speed-zone map and the boat-ramp guide:
 *
 *   src/data/manatee-zones.json  ->  ManateeZonesFile
 *   src/data/boat-ramps.json     ->  BoatRampsFile
 *
 * Both JSON files are GENERATED by `bun scripts/refresh-fwc-data.ts`, which
 * fetches the live FWC (Florida Fish and Wildlife Conservation Commission)
 * ArcGIS layers, normalises them into these shapes, and writes the files.
 * Never hand-edit the JSON; change the script and re-run it.
 *
 * Why a types file at all? `import zones from "@/data/manatee-zones.json"`
 * gives TypeScript a *widened* type (every string becomes `string`), so the
 * literal unions below (ZoneType, etc.) would be lost. The `as...File()`
 * helpers at the bottom re-attach the precise types in one place.
 *
 * Attribution: any UI that renders this data must show the credit lines in
 * src/data/ATTRIBUTION.md (FWC asks to be acknowledged as the data source).
 */

// ---------------------------------------------------------------------------
// GeoJSON geometry primitives (just the two polygon kinds the zones use)
// ---------------------------------------------------------------------------

/** [longitude, latitude] in WGS84 (EPSG:4326), the order GeoJSON mandates. */
export type Position = [number, number];

/** A GeoJSON Polygon: first ring is the outer boundary, any others are holes. */
export interface PolygonGeometry {
  type: "Polygon";
  coordinates: Position[][];
}

/** A GeoJSON MultiPolygon: an array of polygons (each with its own holes). */
export interface MultiPolygonGeometry {
  type: "MultiPolygon";
  coordinates: Position[][][];
}

export type ZoneGeometry = PolygonGeometry | MultiPolygonGeometry;

// ---------------------------------------------------------------------------
// Shared bits
// ---------------------------------------------------------------------------

/**
 * Counties we care about, normalised from the source's shouty values
 * ("INDIAN RIVER", "ST LUCIE", "SAINT LUCIE", "BREVARD"). Typed as a string
 * so a future refresh that pulls in another county does not break the build.
 */
export type CountyName = "Indian River" | "St. Lucie" | "Brevard" | (string & {});

/** [west, south, east, north] */
export type BBox = [number, number, number, number];

/** One source layer that fed a dataset (recorded in `meta.sources`). */
export interface SourceLayerMeta {
  /** Human name of the layer. */
  name: string;
  /** ArcGIS REST layer URL (the `/query` endpoint hangs off this). */
  layerUrl: string;
  /** Owner of the data. */
  publisher: string;
  /** Rows the server returned for our bbox, before our own clip/filter. */
  fetchedCount: number;
  /** Rows kept after clipping to the bbox. */
  keptCount: number;
  /**
   * Newest `last_edited_date` seen on any returned row (YYYY-MM-DD).
   * This is the closest thing the source gives us to a dataset "updated" date.
   */
  sourceLastEdited: string | null;
  /** One-line licence/terms summary. Full wording lives in ATTRIBUTION.md. */
  licenseNote: string;
}

export interface GeoFileMeta {
  /** ISO timestamp of the refresh run that produced the file. */
  fetchedAt: string;
  /** Script that produced the file, so a reader knows how to regenerate it. */
  generatedBy: string;
  /** Clip window used, [west, south, east, north] in degrees. */
  bbox: BBox;
  sources: SourceLayerMeta[];
  /** Record counts by useful groupings (county, zoneType, ...). */
  counts: Record<string, number>;
  /** Short legal/attribution reminder; see src/data/ATTRIBUTION.md. */
  attribution: string;
}

// ---------------------------------------------------------------------------
// Manatee zones
// ---------------------------------------------------------------------------

/**
 * Normalised rule type. FWC's own codes are cryptic (ISAY, SSAY, 30 MPH...);
 * these are the plain-English buckets the UI colours and filters by.
 *
 *  - "no-entry"              all vessels barred (manatee sanctuary / refuge)
 *  - "motorboats-prohibited" no motorboats (paddle craft usually fine)
 *  - "idle-speed"            slowest: minimum speed to maintain steerage
 *  - "slow-speed"            vessel fully off plane, stable wake
 *  - "max-25-mph" / "max-30-mph"  speed ceilings (typically ICW channel)
 *  - "unregulated"           no manatee rule in force (only appears as the
 *                            off-season half of a seasonal zone)
 *  - "unknown"               source code we did not recognise (should be 0)
 */
export type ZoneType =
  | "no-entry"
  | "motorboats-prohibited"
  | "idle-speed"
  | "slow-speed"
  | "max-25-mph"
  | "max-30-mph"
  | "unregulated"
  | "unknown";

/** Month/day window, e.g. Nov 15 -> Mar 31. Windows may wrap New Year. */
export interface DateWindow {
  startMonth: number; // 1-12
  startDay: number; // 1-31
  endMonth: number;
  endDay: number;
}

/**
 * One rule that applies during one part of the year. A year-round zone has a
 * single season with `window: null`; a seasonal zone has two (for example
 * "no entry Nov 15-Mar 31" and "idle speed Apr 1-Nov 14").
 */
export interface ZoneSeason {
  type: ZoneType;
  /** null means "all year". Otherwise the inclusive month/day window. */
  window: DateWindow | null;
  /** Source wording for this part, e.g. "Slow Speed", for traceability. */
  rawClass: string | null;
  /** Source date text, e.g. "NOV 15 - MAR 31". */
  rawDates: string | null;
}

export interface ManateeZone {
  /** Source OBJECTID as a string. Stable across refreshes so diffs stay clean. */
  id: string;
  /**
   * Readable label built from the source's abbreviated description
   * ("Waters within 1000' of W shoreline of the Indian River").
   */
  name: string;
  county: CountyName;
  /**
   * Best-effort waterbody, DERIVED by keyword from the description text. The
   * source has no waterbody field. null when the description says only
   * "as described".
   */
  waterbody: string | null;
  /**
   * Most restrictive rule that applies at any time of year. Use this for the
   * map colour; use `seasons` / zoneRuleOn() for "what applies today".
   */
  zoneType: ZoneType;
  /** true when the rule changes during the year (manatee season zones). */
  seasonal: boolean;
  /** Rules by part of year; always at least one entry. */
  seasons: ZoneSeason[];
  /** Raw source values, kept verbatim so nothing is lost in normalisation. */
  raw: {
    masterClass: string | null; // MASTER_CL
    class1: string | null; // CLASS1_68C
    dates1: string | null; // DATE1_68C
    class2: string | null; // CLASS2_68C
    dates2: string | null; // DATE2_68C
    text: string | null; // TEXT_68C ("Idle Speed (All Year)")
    notes: string | null; // NOTES_68C (abbreviated location description)
  };
  /** Florida Administrative Code citation, e.g. "68C-22.007(1)(a)1.". */
  ruleCitation: string | null;
  /** Free-form data-quality caveat (e.g. the source's dates contradict its text). */
  dataNote: string | null;
  /** true if the polygon was cut at the bbox edge (so the area is partial). */
  clipped: boolean;
  /** Source `last_edited_date` (YYYY-MM-DD). */
  sourceLastEdited: string | null;
  /** [lon, lat] roughly in the middle of the polygon; handy for labels. */
  centroid: Position;
  /** Simplified polygon geometry, 5-decimal coordinates. */
  geometry: ZoneGeometry;
}

export interface ManateeZonesFile {
  meta: GeoFileMeta & {
    /** Douglas-Peucker tolerance used, in degrees (about 1e-5 deg = 1.1 m). */
    simplifyToleranceDeg: number;
  };
  zones: ManateeZone[];
}

// ---------------------------------------------------------------------------
// Boat ramps
// ---------------------------------------------------------------------------

/** Plain-English launch category derived from FWC's RampType. */
export type RampKind =
  | "boat-ramp" // trailer ramp
  | "marina-ramp" // ramp inside a marina
  | "hand-launch" // kayak/canoe/paddle only
  | "airboat-ramp"
  | "other";

export interface BoatRamp {
  /** FWC RampID, e.g. "IR00022YH". Stable key across refreshes. */
  id: string;
  name: string;
  county: CountyName;
  city: string | null;
  address: string | null;
  zip: string | null;
  waterbody: string | null;
  /** e.g. "Salt or Brackish Water" (raw WaterType). */
  waterType: string | null;
  lat: number;
  lon: number;

  kind: RampKind;
  /** Raw RampType, verbatim. */
  rampType: string | null;
  /** Raw AccessType, e.g. "Government Owned for General Public Use". */
  accessType: string | null;

  lanes: {
    single: number | null;
    double: number | null;
    total: number | null;
  };

  fee: {
    /** true/false from Yes/No; null when the source says "Unknown" or blank. */
    required: boolean | null;
    /** Dollar amount if the source gives one (units are not stated by FWC). */
    amount: number | null;
    /** How the fee is collected ("Attendant", "Honor box", ...). */
    collection: string | null;
    /** Free-text rate description if present. */
    rate: string | null;
  };

  parking: {
    vehicleSpaces: number | null;
    trailerSpaces: number | null;
    accessibleVehicleSpaces: number | null;
    accessibleTrailerSpaces: number | null;
    surface: string | null;
    condition: string | null;
  };

  restroom: {
    type: string | null;
    accessible: boolean | null;
  };

  /** FWC "AccessibilityLevel" (ADA-style summary), verbatim. */
  accessibilityLevel: string | null;
  rampSurface: string | null;
  rampCondition: string | null;
  dockType: string | null;
  hours: string | null;
  amenities: string | null;

  /** Raw Status, e.g. "Open for Business", "Temporarily Closed". */
  status: string | null;
  /** true only when Status is exactly "Open for Business". */
  open: boolean;
  statusComments: string | null;
  operationalComments: string | null;

  /** Owner/operator (PrimaryAdminEntity) and partner, if any. */
  operator: string | null;
  partner: string | null;
  phone: string | null;
  /** Operator web page from the source, when provided. */
  url: string | null;

  /**
   * Source row id. The layer URL is the same for every ramp, so it lives once
   * in `meta.sources[0].layerUrl` instead of being repeated 50 times.
   */
  source: {
    objectId: number;
  };
  /**
   * The source's `last_edited_date` (YYYY-MM-DD). NOTE: this is an EDIT date
   * in FWC's database, not proof someone re-surveyed the ramp that day.
   */
  lastVerified: string | null;
}

export interface BoatRampsFile {
  meta: GeoFileMeta;
  ramps: BoatRamp[];
}

// ---------------------------------------------------------------------------
// Typed loaders + helpers
// ---------------------------------------------------------------------------

/**
 * Re-attach precise types to the imported JSON:
 *   import raw from "@/data/manatee-zones.json";
 *   const data = asManateeZonesFile(raw);
 * (A plain cast; the refresh script is the only writer so the shape is trusted.)
 */
export function asManateeZonesFile(json: unknown): ManateeZonesFile {
  return json as ManateeZonesFile;
}

export function asBoatRampsFile(json: unknown): BoatRampsFile {
  return json as BoatRampsFile;
}

/** Is month/day inside an inclusive window (handles windows that wrap the new year)? */
function inWindow(w: DateWindow, month: number, day: number): boolean {
  // Encode month/day as one sortable number: Nov 15 -> 1115.
  const here = month * 100 + day;
  const start = w.startMonth * 100 + w.startDay;
  const end = w.endMonth * 100 + w.endDay;
  return start <= end ? here >= start && here <= end : here >= start || here <= end;
}

/**
 * Which rule is in force on a given date? Returns the ZoneSeason that applies,
 * or null if the zone's seasons do not cover that date (should not happen for
 * complete data). `date` defaults to now; month is read in local time, so pass
 * a Date built for America/New_York if the server runs in UTC.
 */
export function zoneRuleOn(zone: ManateeZone, date: Date = new Date()): ZoneSeason | null {
  const month = date.getMonth() + 1;
  const day = date.getDate();
  for (const s of zone.seasons) {
    if (s.window === null || inWindow(s.window, month, day)) return s;
  }
  return null;
}
